### PR TITLE
fix: attributes/addClass, the wrong checking on class-name inclusion

### PR DESCRIPTION
**Pull request by olegmedoed**

### CODE REVIEW

**Comment by shshaw** [comment]
Can you explain the change a bit? It looks like this is to fix an issue when checking for a class that would be at index `0`, just want to be sure.

**Comment by olegabyst** [comment]
I think here supposed to be a check that class isn't added twice(what my fix is supposed to make true), am I correct?

**Comment by shshaw** [comment]
Yes, preventing doubled classes is the intention, but pretty much only for IE9 where `classList` isn't supported. Your correction fixes when the class has a space in front of it and it is the first class, though looking at this now there are plenty of cases where that statement won't trigger correctly. This should probably be changed to:

```

function addClass(v,c,spacedName){
  if (v.classList) { v.classList.add(c); }
  else if ( !hasClass(v,c) ) { v.className += ' ' + c; }
}

...

fn.extend({

  addClass(c){
    var classes = getClasses(c);

    return ( classes ?
      this.each(v => {
        each(classes,c => { addClass(v,c); });
      }) :
      this
    );
  },

...
```

**Comment by olegabyst** [comment]
I'm sorry, I just accidentally confuse operator, I mean
```
  if (v.classList) { v.classList.add(c); }
  else if ( spacedName.indexOf(`${c}`) === -1 ) { v.className += ' ' + c; }
```
and, yes, I think your case ..
```
  else if ( !hasClass(v,c) ) { v.className += ' ' + c; }
````
.. is most correct, should I rewrite code in this way and make commit?

**Comment by shshaw** [comment]
Good catch.

Yes, please rewrite as mentioned using `hasClass` and dropping that `spacedName` variable in `addClass`. Run a few tests to make sure it's working as expected (particularly in IE9) and I'll accept the pull request.

**Pull request merged**
