### PR TITLE
Fixed delegated events to receive the event object

### PR DESCRIPTION
**Pull request by tjbenton**

### CODE REVIEW

**Comment by shshaw** [comment]
[Line 39](https://github.com/kenwheeler/cash/pull/109/files#diff-34a6d62af0cf0b784f8444529f3130efR39) should just be `);` instead of the `.call` part.

```
function matches(el, selector) {
  var m = el && (
    el.matches ||
    el.webkitMatchesSelector ||
    el.mozMatchesSelector ||
    el.msMatchesSelector ||
    el.oMatchesSelector
  );
  return !!m && m.call(el, selector);
}
```

**Comment by tjbenton** [comment]
I forgot to rebuild the file on that last push so you might need to stop the travic-ci test and rerun it.

One of these days I will get more familiar with git on the command line.

**Comment by shshaw** [comment]
I still don't get git (hehe) via command line. The [Github Desktop app](https://desktop.github.com/) or [SourceTree app](https://www.sourcetreeapp.com/) are both super helpful to visually understand what's happening with the commits.

**Comment by tjbenton** [comment]
I've been using [git tower](https://www.git-tower.com/) and it's pretty good too, the only thing it doesn't allow you do to is a force push onto a branch.Which isn't a big deal for the most part as long as you don't have to squash commits that you've already pushed to the remote.

**Comment by shshaw** [comment]
@simeydotme Can you check this with your updated test suite before we merge?

**Comment by simeydotme** [comment]
@shshaw I'm just writing the tests for this fast, gimme a few mins before merging `1.3.0`, please ? :)

**Comment by shshaw** [comment]
Will do. I'm trying to figure out a better way to merge them all instead of applying them all to the master branch directly then doing a 1.3.0 version bump, so it will likely be later this afternoon until it's ready.

**Comment by simeydotme** [comment]
### with cash from master
screenshot 160505 002453

-----

### with 109 build
screenshot 160505 002513

Also all the tests I currently have for dom selection (the tests that run through `matches()`) all pass, so...
LGTM ! :)

**Comment by simeydotme** [comment]
@shshaw you use the GUI, right? it's super easy with the command line

**Comment by shshaw** [comment]
Great to hear about the tests.

I do primarily use the GUI, and due to [GitHub Issue 18](https://github.com/isaacs/github/issues/18) that isn't really supported. 

In all my Googling, I can't find a straightforward way to merge the PRs into a separate branch using the command line either. Have a suggestion?

**Comment by simeydotme** [comment]
Ok, so basically... you have you 1.3.0 branch. 
You need to set up the contributor's cloned repos as `remotes` ... 

For example: 
```
git remote add tj https://github.com/tjbenton/cash.git && git fetch tj
```
(this will also download information about all their branches, with `fetch`)

now you can merge any of their branches (assuming you're still on your `1.3.0` branch):
```
git merge remotes/tj/bugfix/on-event
```

If you're merging in your own branches on the `kenwheeler` repository, you don't need to do the remote shenanigans... just `git fetch` to make sure you have up-to-date info on the branches.

---

If it would help, I'm already half-way through doing this... and can just push the branch to my repo for viewing... however I'd strongly advocate attempting this yourself (even if it fails miserably) as the command line is a path to many abilities... some even considered.... unnatural. :stuck_out_tongue_closed_eyes:

**Comment by shshaw** [comment]
Hah, I will try it out, but if you're already most of the way there then feel free to do it.

**Comment by simeydotme** [comment]
https://github.com/simeydotme/cash/tree/1.3.0-a :)
if it looks OK, I can squash the merge commits in to the 1.3.0 , and push to Ken's repo... then you can tag it up and prepare a release note? :)

**Comment by shshaw** [comment]
Definitely some magic happening from your command line abilities! I got stuck after the first merge conflict :-) 

Yours looks good to me. I'm going to double check the documentation in README.md and make a few updates as needed. 

For these pull requests, will they just be closed out without true 'merging'?

**Comment by simeydotme** [comment]
I can close them by rewriting the commit message with "resolves" :)
Gimme a few mins :bow: 

(as for the conflicts, those are mostly due to the dist folder... if you ever get the urge to try again, just run: `git reset ./dist && git checkout -- ./dist` after the merge conflicts appear... that will remove the dist folder from the merge, and allow you to finally build the `/dist` after merging :)

**Comment by shshaw** [comment]
Again: magic. Thanks a ton!

**Comment by simeydotme** [comment]
No problem! :D

https://github.com/kenwheeler/cash/commits/1.3.0
thre you go dude... that branch is looking good now, just pull it again locally, and do your wonderful stuff... I'm off to bed now, Hope to see a shiny new version tomorrow! :D 

(I didnt tag it, that's for you)

**Pull request merged**
