### PR TITLE
Class Method fixes

### PR DESCRIPTION
**Pull request by simeydotme**
I was doing some shenanigans, and found a fairly bad script-killing error when trying to use `.addClass();` ... my classname was being generated, but it turned out `falsey`... hell broke loose :fire: .

I've amended the various css class manipulation methods to check for `truthy/string` values before attempting to run native `classList` operations on the values. 

This 
- more closesly resembles jQuery, (https://github.com/jquery/jquery/blob/master/src/attributes/classes.js#L27 ) 
- adds only a tiny amount to weight 
- has no discernible performance impact.

Would appreciate a quick once-over from @shshaw / @kenwheeler before I merge :bow:

### CODE REVIEW

**Comment by shshaw** [comment]
Good catch! 

We do already have an `isString` function. :-) I think there might be a way to unify this a bit more. Let me take a pass.

**Comment by simeydotme** [comment]
thanks, @shshaw for that! :D just updated to `isString()`. -- interestingly, it didn't even affect the minified file, hehe.

I'm going to bed now, have fun...

**Comment by shshaw** [comment]
Started a branch at [pr/110](https://github.com/kenwheeler/cash/tree/pr/110) with an alternate method.

**Comment by simeydotme** [comment]
@shshaw I merged your pr/110 branch back to mine, and also added the ability to remove all classes by supplying zero arguments: https://github.com/kenwheeler/cash/pull/110/commits/8428c877010cf190430f57bffa336ee16a45e79d#diff-c4c92b97ff60ec14a1199df1f5ae644eR92 :)

**Comment by shshaw** [comment]
Good catch on the 'remove all classes' functionality. Hadn't used that before, but that is something that jQuery provides that is definitely useful.

My only thought would be instead of checking for `arguments.length`, a simple ` ( !c ) ` check may suffice, though that would mean `removeClass(false)` and `removeClass(null)` and `removeClass(undefined)` would also remove all classes. Don't know if that would be expected behavior.

**Comment by simeydotme** [comment]
I thought about that, and found it's too unpredictable... if you try to remove a class with a variable, and it becomes `undefined`, you probably wouldn't expect it to remove all classes, you'd expect it to remove no classes.

Try this:

```js
var x = $("input").val();       // => if this is empty
$( "body" ).addClass( x );      // => expect this to add nothing
$( "body" ).removeClass( x );   // => _dont_ expect this to remove all classes

**Comment by shshaw** [comment]
Yes, I think you're right.

**Pull request merged**
