### PR TITLE
Setup karma test runner + TravisCI

### PR DESCRIPTION
**Pull request by limonte**
In order to be Community-friendly and truly opened for contributions, CI is a must. Contributors will instantly see the status of their features/fixes and take actions if tests are failing.

Karma is extremely configurable test runner which will allow (if needed) to set up the cross-browser, cross-platform tests, see how we set up karma for SweetAlert2: https://github.com/sweetalert2/sweetalert2/blob/master/karma.conf.js

1 test (`offsetParent`) is currently failing in CI, I would appreciate if you can help me with it @fabiospampinato 

Thanks a lot for creating `cash`, I'll ship it to the production server of my project this weekend and report issues if there are some. So far, 💰  works just perfectly!

The next step after merging this PR would be setting up the AppVeyor CI to test in lovely IE11 :)

### CODE REVIEW

**Comment by limonte** [comment]
Alright, the PR is ready for review, 1 test is failing. @fabiospampinato would you mind to take a look on the PR and the reason why the `offsetParent` test is failing?

**Comment by limonte** [comment]
> Template strings aren't supported in IE11 I think, you'll have to remove them.

Done.

There's 1 failing test in IE11: 
image

It's known and reported: https://github.com/kenwheeler/cash/issues/186

**Comment by fabiospampinato** [comment]
Nice, thanks for taking the time to debug this.

I've merged the PR, with a few minor changes:

1. I've removed the badge from the readme, I don't really like those things
2. I've changed the coding style a bit
3. I've replace the use of `$.fn.html` from inside QUnit's `beforeEach` function with plain DOM API calls, it doesn't really change anything but I don't think we should use things that we are actually testing there
4. There's a new `test:karma` script, for running karma locally

> There's 1 failing test in IE11:
> It's known and reported: #186

I've changed the test, now we are passing `<a></a>` to `$.parseHTML`,  instead of `<a>`, which one isn't really supposed to be doing.

Since you're planning to use `cash` in production you might want to run its methods against jQuery's test suite, you should be able to do so with just a `npm run test:jquery`. jQuery's `parseHTML` handles a lot more weird cases that ours, such as unclosed html tags, `<tr>` elements without a table etc. I don't think it's worth fixing those incompatibilities unless the code required to do so is quite small.

Feel free to submit other PRs adding support for multiple browsers to karma, it would be nice if we could add Firefox's latest, Edge's latest and IE11 👍

**Comment by limonte** [comment]
Perfect! Thank you @fabiospampinato!

> Feel free to submit other PRs adding support for multiple browsers to karma, it would be nice if we could add Firefox's latest, Edge's latest and IE10

For that, we'll need to set up SauceLabs account, it's free for OSS. Please create an account: https://signup.saucelabs.com/signup/trial then contact hello@saucelabs.com and ask them to transform free trial account to free OSS account.

After that, please add two secure variables - `SAUCE_USERNAME` and `SAUCE_ACCESS_KEY` in Travis settings of the project.

Let me know when you're done with those steps, I'll handle the rest 🚀

**Comment by fabiospampinato** [comment]
I'll let you know when it's done 👍

**Comment by limonte** [comment]
FYI, SauceLabs might ask you to mention them in README of the project. We're using this template: https://github.com/vaadin/vaadin-tabs/commit/860c807bfc8d3e6a0acd10bdd6cd2e3d96f00182

**Comment by fabiospampinato** [comment]
@limonte I've created an account and contacted them, I'm waiting for their response.

**Comment by limonte** [comment]
> I've created an account and contacted them, I'm waiting for their response.

:+1:

From my experience it should take 1-3 working days for them to reply. If it takes longer it might be worthy to ping them :)

**Comment by limonte** [comment]
Hello @fabiospampinato, any news from SauceLabs?

**Comment by fabiospampinato** [comment]
Hey, sorry for the delay, they upgraded the account last saturday, I'll tell ken to add the environment variables and I'll let you know when it's done 👍

**Comment by limonte** [comment]
Roger, it should be something like this:

image

The settings page is https://travis-ci.org/kenwheeler/cash/settings

**Comment by fabiospampinato** [comment]
It looks like I can add environment variables myself, it's all set 👍

**Pull request merged**
