### PR TITLE
Added README logo

### LINKED ISSUE #194: 💰cash logo suggestion
Hi everyone! 👋

A couple of days ago I published a small roundup of some of the [best resources](https://designrevision.com/resources-for-web-developers-and-designers-may-2018/) for the past month for web developers and also [included](https://designrevision.com/resources-for-web-developers-and-designers-may-2018#cash-js) `$cash` in the list.  I noticed that it had no logo yet so I spent a few minutes trying to create one and I was wondering what do you think about it?

Based on the feedback and ideas I'll get, I can iterate and come up with something more polished if necessary. Let me know your thoughts.

🍻Cheers!

rfwdd_cash

### PR DESCRIPTION
**Pull request by hisk**
Fixes #194.

@fabiospampinato I used a slightly different font and added a *really* subtle gradient. Let me know your thoughts. 😄

### CODE REVIEW

**Comment by fabiospampinato** [comment]
It looks great, thanks.

The only weird thing are the single quotation marks, I think they usually look like a slim rectangle on the fonts used for programming, those used in the logo seem made for being used as in `L'amore`, not for actually quoting strings :thinking: could you fix that?

It would be great if you could share the `.psd` as well. 

I'm currently on vacation, I'm going to merge this on early July. 

Thank you.

**Comment by hisk** [comment]
@fabiospampinato Sorry for the delay. I attached 3 more variations using different monospaced fonts. Let me know which one do you think would work better and/or if I should make some more adjustments. 😄 

🙃 *I know the 1st and 3rd examples look almost the same, but they're not.*

cash_logos_preview

**Comment by fabiospampinato** [comment]
@hisk thanks, let's go with the first one 👍 The only thing I would change would be having the quotation marks symmetrical on the y axis, it's a bit weird to my eyes to have them kind of rotated a bit 🤔but it's also ok like this, I don't want to take too much of your time.

**Comment by hisk** [comment]
@fabiospampinato Don't worry about it, it's the least I can do. 😄 Please let me know your thoughts on this one and don't hesitate if you'd like more changes.

**Comment by fabiospampinato** [comment]
@hisk, that's perfect, thank you!

**Comment by hisk** [comment]
@fabiospampinato I updated the logo and attached the `.psd` below (zipped as GH won't allow `.psd` file uploads). Let me know if you'd like me to commit it inside the repo instead.

[cash-logo.psd.zip](https://github.com/kenwheeler/cash/files/2167610/cash-logo.psd.zip)

**Comment by fabiospampinato** [comment]
@hisk I've just added the logo to the repo, I've just made a few little changes:

**Pull request closed without merging**
