### PR TITLE
Normalize all text file in the repo.

### PR DESCRIPTION
**Pull request by vivekimsit**
Normalize all text file's line ending in the repository to LF https://git-scm.com/docs/gitattributes

### CODE REVIEW

**Comment by vivekimsit** [comment]
@shshaw can you please take a look at it?

**Comment by shshaw** [comment]
I'm not the most educated on git. @simeydotme any thoughts?

**Comment by simeydotme** [comment]
umm, yeh... I've never seen this needed before, `git` is usually set to automatically change `cr` to `lf` when committing, unless we've run into instances where someone's changed the line endings of files and caused a huge `diff-mess` , then I don't think that this is needed? but equally; it won't cause any harm...

**Comment by vivekimsit** [comment]
@simeydotme I just wanted to follow the standards like [here](https://github.com/sindresorhus/cp-file/blob/master/.gitattributes).

**Pull request merged**
