### PR TITLE
chore(tests): bump qunit to latest

### PR DESCRIPTION
**Pull request by limonte**
I'm going to submit a PR which will enable CI tests in Travis.

This one is the preparation for that.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
👍

**Comment by limonte** [comment]
Thanks for merging @fabiospampinato! would you mind to enable TravisCI for this project so my upcoming PR will be tested in it?

**Comment by fabiospampinato** [comment]
I think it's enabled already. Anyway only the owner can change these things.

---

I see GitHub Services are going to be [discontinued](https://developer.github.com/v3/guides/replacing-github-services/) in January, they are transitioning to GitHub Apps and WebHooks, I'm not sure if that means our Travis CI integration will break or not 🤔

**Comment by limonte** [comment]
> I see GitHub Services are going to be discontinued in January, they are transitioning to GitHub Apps and WebHooks, I'm not sure if that means our Travis CI integration will break or not 🤔

No, that's unrelated to TravisCI, everything will be fine :)

**Pull request merged**
