### PR TITLE
Toggle class

### PR DESCRIPTION
**Pull request by simeydotme**
Updated the `hasClass` method and added a `toggleClass` method, both now will work on the entire collection and accept multiple classes.

`hasClass` will return `false` if __any__ of the items in the collection do __not__ have the given class(es); - to revert to the original behaviour it's as simple as `$("el").first().hasClass("className");`

Hope you like it, I htink it's a good improvement on the default functionality and another `1up` on jQuery?

Creating in response to #46

### CODE REVIEW

**Comment by gamebox** [comment]
It would be interesting to know what's the status with this.  It's a tad confusing to have toggleClass in the docs, but not actually in the codebase.  Something I can do to help?

**Comment by simeydotme** [comment]
Seems this method was copied/converted in a large merge with another library in #66 ... Not sure if that was released yet... The `readme`  unfortunately always takes the master trunk, and not the latest release... So it's usually ahead of the stable release (hence the method is in the docs, but not the releases code)

**Comment by gamebox** [comment]
Ah, thanks @simeydotme .  So I would suggest closing this, and discuss how to keep releases and docs in sync.

**Comment by shshaw** [comment]
Both of these fixes were implemented in different ways as of version 1.1.0. Thanks!

**Comment by simeydotme** [comment]
@shshaw ... did you implement my `.hasClass()` method with the same functionality? seems not... I'm just writing unit tests now based on my previous set; and it's failing for:

```
<i class="a b x y  "></i>
<i class="a b x    "></i>
<i class="a b   y z"></i>

$("i").hasClass("x y z"); // errors, because checking for multiple classes;
```
It doesn't handle multiple classes, just crashes. It should make sure all classes are present as was the case with my PR... and is the case where `.toggleClass()` will toggle all the classes?

I know that actually my PR was never really reviewed/accepted by @kenwheeler , and so I'm willing to accept the default _loose checking_ change.. as it is the same as jQuery... however I really think that the multiple class checking is a bug?

**Comment by shshaw** [comment]
It was my own implementation of `hasClass`, likely adapted from my old halfDollar library, and you are correct, it does not check for multiple classes. `toggleClass`, `addClass` and `removeClass` do all handle multiple classes, so I can see where that may be an issue.

jQuery doesn't document having the ability to check for multiple in their `hasClass` and I've never used `hasClass` to check for multiple classes. What is the expected behavior? Is it 'has all' ( `x AND y AND z` ) or 'has any' ( `x OR y OR z` )? Looking at your code, it looks like it's "has all", I just want to be clear.

**Comment by simeydotme** [comment]
Thanks for getting back, @shshaw  :grinning: 
Yeh, that's right; `jQuery` doesn't support this so it'd be nice to have another `1up` there... if we look at it pragmatically;

- `.addClass("big bold red")` adds all classes
- `.removeClass("big bold red")` removes all classes
- `.toggleClass("big bold red")` toggles all classes

so it seems to make sense that:

- `.hasClass("big bold red")` checks all classes

imagine something like:

```
var classes = "big bold red";
var $btn = $("button");

$btn.toggleClass( classes , $btn.hasClass( classes ) );
```
having it return true for just one of the classes would be strange.

**Comment by shshaw** [comment]
I wonder if it might be best to have these as separate methods. `hasAnyClass('x y z')`, or `hasAllClass('x y z')`?

**Comment by simeydotme** [comment]
well that's a logical step, but then it seems like we're just shortening the user's work for:
```
( $.hasClass("x") || $.hasClass("y") || $.hasClass("z") )
```
or
```
( $.hasClass("a") && $.hasClass("b") && $.hasClass("c") )
```

So i'd say that's not work we need to do. 
Perhaps it's a design question and ken should weigh in... my thoughts are just consistency across similar interfaces with slight efficiency gain when possible :grin:

**Comment by shshaw** [comment]
It's definitely a shortcut, but so are all of these methods 😄 
We'd need to consider the amount of weight added for the methods vs the benefits. If these checks are a common need, then implementing them is worthwhile.

**Pull request closed without merging**
