### PR TITLE
Traversal fixes

### PR DESCRIPTION
**Pull request by shshaw**
# Fixed
- `$.fn.siblings` and `$.fn.has` now return a Collection instead of an Array.
- `$.fn.closest` returns an empty collection instead of the current collection if no selector provided
- `$.fn.closest` correctly checks all items in the collection, not just the first.
- `$.fn.filter` returns the collection as-is if no selector provided.

# Added
- `$.fn.is`, `$.fn.not`, `$.fn.has`, `$.fn.find`, `$.fn.filter` and `$.fn.closest` now support an element as the argument instead of a string based selector. ( #132 )

### CODE REVIEW

**Comment by shshaw** [comment]
@simeydotme I've changed a test or two to match the new functionality, but could use some help building tests that will test the fixed and added functionality. Think you can spare some time to add the extra tests?

**Comment by simeydotme** [comment]
hey @shshaw :)
yeh, sorry I've been so lax last few weeks, I want to get back into the unit tests full swing on the other branch... gonna have to look at how to rebase with all the recent updates. I don't really want to put effort into QUnit as it hasn't got coverage reports or anything and it's already missing a ton of stuff.

**Comment by vivekimsit** [comment]
@simeydotme what about using karma with jasmine?

**Comment by simeydotme** [comment]
yeh @vivekimsit that's what I'm doing on another branch :)
moving all tests to a CLI/NPM based testing framework which can be run from Travis CI,

You can view it, but it's still work in progress :) 
https://github.com/kenwheeler/cash/tree/npm-scripts/test

I would suggest to maybe add some base-line tests in the current qUnit, @shshaw just to make sure there's some sanity checking going on and it's not breaking anything... it'll take too long to wait for the npm-scripts branch to be up to snuff :) :bow: 

apologies

**Pull request merged**
