### PR TITLE
$.each for objects

### PR DESCRIPTION
**Pull request by shshaw**
#104

### CODE REVIEW

**Comment by shshaw** [comment]
@simeydotme The test for this fails, but it does work. It seems like there may be some sort of async issue. I couldn't find a way to test it that works, but if you try it in the console you can see that it does work.

**Comment by shshaw** [comment]
Looks like it may be due to something about how `new Array` works. If you create an empty array manually, it works fine ( `[undefined,undefined,undefined]` ).

**Comment by simeydotme** [comment]
let me take a quick look later :) are you referring to the test in QUnit ?

**Comment by shshaw** [comment]
In test.js. Those are the QUnit tests, but you've been setting up a
different test platform, right?

**Comment by shshaw** [comment]
@simeydotme Did you ever get a chance to check the testing for this out?

**Comment by fabiospampinato** [comment]
Closing this as it's a very old PR, feel free to re-submit it again if you think it's appropriate.

**Pull request closed without merging**
