### PR TITLE
Added very simple AJAX support.

### PR DESCRIPTION
**Pull request by TheGreatPanda**
I added some really simple AJAX support. I'm not entirely sure if it's in line with the project, but I thought I'd just submit a pull request. It currently only supports GET and POST. This is the syntax:

``` js
    $.ajax("https://httpbin.org/", {}, function() {
        console.log(this.responseText);
    })

    $.ajax("https://httpbin.org/post/", {method: "POST", postParams: {name: "TheGreatPanda", repo: "kenwheeler/cash"}, function() {
        if(this.status != 200) {
            console.log("Error posting!!1");
        } else {
            console.log("All's well");
        }
    });
```

### CODE REVIEW

**Comment by shshaw** [comment]
Thanks for taking the time to put that together. This functionality is something we've been discussing on #103 (with some example code). If it is implemented, it will likely be as a separate file that can be included if your project requires. `/dist/extras/cash.ajax.min.js` or something similar.

I'll definitely take a look at your code to see how we can get this functionality to a good state. Feel free to contribute to the discussion on #103. Thanks!

**Comment by TheGreatPanda** [comment]
Thanks for the feedback!

**Comment by TheGreatPanda** [comment]
Is anybody still looking at this?

**Comment by shshaw** [comment]
Pretty much just me maintaining cash these days. Right now, there are some more pressing bugfixes and improvements in the pipeline, and I'm slammed with my dayjob. I don't know exactly when AJAX may be looked at.

Feel free to write a plugin as a separate repository and I can link it from the README. If enough traction gets gained, then we may be able to roll it into the main library.

**Comment by vivekimsit** [comment]
I wouldn't go for the ajax support that would make cash overburden and more hectic for maintainers, it should be DOM only affair.

**Comment by shshaw** [comment]
@vivekimsit This is the discussion we've had on #103. Once a basic implementation is in place, then it shouldn't be difficult to maintain, and it would be offered as a separate file to not increase the library's size.

**Comment by shshaw** [comment]
Again, the functionality is something that's worthwhile and there aren't any lightweight options that I've been able to find. Fetch isn't prime-time ready, the poly-fill is huge, and the syntax is quite foreign. A simple equivalent to jQuery's ajax would be extremely helpful for cases where you just need to grab something dynamically or send data back.

**Comment by vivekimsit** [comment]
@shshaw its not about size its about responsibilities there are already fully tested ajax libs out there, I have no issue but you yourself said in previous comment that you are overburdened.

**Comment by tjbenton** [comment]
[`unfetch`](https://github.com/developit/unfetch) is a good fetch polyfill that's really small

> Bare minimum fetch polyfill in 500 bytes

**Comment by DanielRuf** [comment]
whatwg-fetch, promise-polyfill + fetch should be sufficient

**Comment by pwFoo** [comment]
Maybe use https://github.com/typicode/fetchival?

**Comment by fabiospampinato** [comment]
Closing this as it's a very old PR.

Please read [this](https://github.com/kenwheeler/cash/issues/103#issuecomment-395983433) comment and feel free to re-submit it again if you think it's appropriate.

**Pull request closed without merging**
