### PR TITLE
Added $.type

### PR DESCRIPTION
**Pull request by softwarespot**

### CODE REVIEW

**Comment by simeydotme** [comment]
Yo :)
JSPerf is down, so I jsut spent way more time on this than I should have, lol...

https://jsfiddle.net/qdtsozLv/2/
Please let me know if I made a mistake in the tests, but I think they should be good?

**Comment by shshaw** [comment]
Are higher numbers better in your performance test? On iOS Safari, I'm
seeing around 4.3 for the Cash version and 0.4 or so for jQuery.

**Comment by simeydotme** [comment]
*(updated the fiddle)*, 

you can also see that 
- `cash` returns `nan` 
- `jquery` returns `number` 

for the `nan` test... wonder if we should align?

**Comment by simeydotme** [comment]
@shshaw i coloured them to signify :P ... higher = takes longer to run... although that is for `200,000` executions a pop.. so 2ms is negligable for most of the tests, but string/number/nan seems  to be majorly in jquery's favour

**Comment by simeydotme** [comment]
https://jsfiddle.net/qdtsozLv/5/ `added number, ordered test by alphabet`

**Comment by softwarespot** [comment]
This type is different than jQuery's as I read cash isn't so much about being a jQuery clone.

**Comment by simeydotme** [comment]
hye @softwarespot :) not sure exactly... having a check for `NaN` does seem to be ***better*** than jQuery's implementation, but it would wreck any code conversion which does: 
```js
var formVal = parseInt( "six" ); // some crap you might get
var n = $.type( formVal ); // the type of the crap
return n === "number" && !isNaN( formVal ); // lol, I've totally seen code like this before.
``` 
I'm not making a statement, just raising discussion :)

**Comment by simeydotme** [comment]
and the unit tests should ideally test all types, not just `func/string/num`

**Comment by softwarespot** [comment]
@simeydotme Testing all types is a little over the top, as it simply passes the variable to Object.prototype.toString, which returns the internal [Class] name.

**Comment by simeydotme** [comment]
@softwarespot , that's how it currently works :smile: ... 

the tests are there to ensure it always returns that same value, no matter how the internals of the library, or the method, are changed over time 😁 ... If I come back in 3 months, and decide to modify that method to do something other than `Object.prototype.toString()` (I probably wont, but)... there's no tests to ensure the result remains the same.

-- and I know "the current tests are not all like that" ... which is exactly why I'm rebuilding them... hehe. So you can/can not test all the possibilities... as I will do it eventually... but it'd be a help if you could so I just have to convert them :bow:

**Comment by softwarespot** [comment]
Yeah but what types should be tested? As you said all types and that just isn't feasible since there are a lot of types to test.

```js
var el = document.querySelector('a');

// Returns [object HTMLAnchorElement]
console.log(Object.prototype.toString.call(el));
```

**Comment by simeydotme** [comment]
Right, then ... is that expected behaviour?.. 
jQuery returns `object` for anything that begins with `[object ...]` ... it'd basically be denying any interchangeability

**Comment by softwarespot** [comment]
That's expected behaviour, which is why this is totally different to how jQuery does it. Some users might want to know if an object of a specific type.

**Comment by simeydotme** [comment]
hmmm... then I think I have no answers here, just more questions... so it'd be good to get a design decision from the man himself: @kenwheeler :dancer: thanks for talking it through with me, @softwarespot ! :bow:

**Comment by kenwheeler** [comment]
screen shot 2016-04-25 at 7 56 31 am

@simeydotme hasn't javascript already made that decision?

**Comment by shshaw** [comment]
Thoughts on performance: Moving the `reTypeOf` regex outside of the function itself so it can be cached, and simplifying it to `/\[object\s(.*?)\]/` should speed it up quite a bit.

May also be worth testing `String.replace` vs `String.match` and `RegExp.exec`. Too bad JSPerf isn't accessible.

**Comment by shshaw** [comment]
Looking at [jQuery's `type` implementation]https://github.com/jquery/jquery/blob/91850ecbbe04ad8f5d89dc050aa1d9002047c435/src/core.js#L260, they have [an array of all the `type` possibilities](https://github.com/jquery/jquery/blob/91850ecbbe04ad8f5d89dc050aa1d9002047c435/src/core.js#L453), instead of a RegEx check. The array lookup is definitely going to be faster than a RegEx check, wouldn't be difficult to implement something similar, though the RegEx feels cleaner to me.

**Comment by softwarespot** [comment]
What about this? https://jsfiddle.net/gxdg69rb/

**Comment by shshaw** [comment]
Here's the Fiddle with some small tweaks and the performance testing code: https://jsfiddle.net/qdtsozLv/6/

The cache doesn't seem to help much, oddly enough.

**Comment by shshaw** [comment]
Looks like jQuery's speed advantage may be more related to the [`typeof` checks](https://github.com/jquery/jquery/blob/91850ecbbe04ad8f5d89dc050aa1d9002047c435/src/core.js#L266), where it only uses the `toString` cache call if the `typeof` is `"function"` or `"object"`

**Comment by shshaw** [comment]
[This updated jsFiddle](https://jsfiddle.net/qdtsozLv/8/) seems to be much more on par with jQuery's performance, at least in Chrome.

**Comment by softwarespot** [comment]
I came up with this >> https://jsfiddle.net/qdtsozLv/9/

**Comment by shshaw** [comment]
v10 seemed to have great performance. I made a few adjustments to clean up the code: https://jsfiddle.net/qdtsozLv/11/

**Comment by simeydotme** [comment]
wow, great work guys !! :)
I'm seeing cash on par/better performing than jQuery in that last fiddle for most tests, and when not; it's totally negligible!

---

so just the highlights from me, I'm happy with the outcomes above, but still just a little fuzzy on the aesthetic;

1 ) _Should we be returning strings of the internal class, as @softwarespot has implemented, or should we keep `$.type` on parity with jQuery and return general `object`s ?_
```js
jQuery.type( window ); // => 'object'
  cash.type( window ); // => 'global' 

jQuery.type( document.querySelector('div') ); // => 'object'
  cash.type( document.querySelector('div') ); // => 'htmldivelement'

jQuery.type( parseInt( "six" ) ); // => 'number'
  cash.type( parseInt( "six" ) ); // => 'nan'
```

1.1 ) _Or should we consider a secondary `boolean` option `$.type` method for the functionality that @softwarespot has implemented? eg:_

```js
cash.type( window )        // => 'object'
cash.type( window , true ) // => 'global' 

cash.type( parseInt( "six" ) )       // => 'number'
cash.type( parseInt( "six" ), true ) // => 'nan' 
```

2 ) _How much value is it to know the low-level type of something?_

**Comment by kenwheeler** [comment]
I think the jquery style implementation is the more useful of the two personally

**Comment by shshaw** [comment]
Not sure why `window` would be returning `global` as the type, anyway. It should be returning either `object` or `window`:

```javascript
> typeof window
"object"
> Object.prototype.toString.call(window)
"[object Window]"
```

**Comment by shshaw** [comment]
As per @kenwheeler's input, I do think with a modification to return `object` instead of the more specific type is better in terms of usability. 

@softwarespot feel free to make those changes, and then we'll look at implementing this for 1.4.0

**Comment by softwarespot** [comment]
@shshaw So just to clarify, you want it to be like typeof but can recognise variables that are created with constructors e.g. String(someVar) would be an object with typeof, but string with toString.call.

**Comment by shshaw** [comment]
@softwarespot Correct. It may need to be a whitelist implementation like jQuery's array where anything else returns 'object'.

**Comment by softwarespot** [comment]
Okay, I will do it tomorrow now, with a slightly enhanced "white-list"

**Comment by softwarespot** [comment]
I am kind of busy at this moment, so I will close this PR for now since it has changed from my original implementation.

**Pull request closed without merging**
