### PR TITLE
`after`, `before` & fixed `insertAfter` & `insertBefore`

### PR DESCRIPTION
**Pull request by shshaw**
- Collection support for `insertBefore` and `insertAfter`
- Added `after` and `before`
- Updated documentation

### CODE REVIEW

**Comment by simeydotme** [comment]
@kenwheeler .. are you checking the performance of these merges?
As a random sample: http://jsperf.com/shshaw-vs-jquery/6 ... I remember performance was a key consideration way back when :)

**Comment by kenwheeler** [comment]
@simeydotme interesting, I was under the impression that their select was more performant. I was gonna run through before releasing, but thanks for getting that started.

**Comment by shshaw** [comment]
I'll double check the code. My after and insertAfter might be reversed in
terms of how the code is utilized, so insertAfter would probably be more
performant for tests. Overall, unless you're appending thousands of items,
there likely won't be a noticeable difference between jQuery and my method.

The previous insertAfter etc would only work for the first element in the
collection and for the first parent of the target and would create a clone
of the element because outerHTML was used, which would likely cause some
DOM thrashing and performance compromises.

That said: what exactly is the primary target for cash: performance, file
size, or working with elements & collections as expected?

Obviously all are ideal, and feature parity with jQuery isn't the goal, but
each one requires consideration. We may be in one of those "choose two"
situations for some methods.

**Comment by shshaw** [comment]
For the record, my main goal with these rewrites has been ensuring the methods work as expected (i.e. with collections and not just first element, no cloning unless necessary, etc) and trying to keep the code consistent and the file size as trim as possible.

Some ideas for the most important performance tests:

- jQuery collection building vs my method vs previous cash method, specifically targeting DOM Elements, element selectors, IDs, classes, and building HTML from a string
- addClass/removeClass
- append
- css: getting, setting & with an object
- each
- parent

These tests should show if the overall methods used are equal, better or worse in performance and if more rewriting should be considered.

**Pull request closed without merging**
