### PR TITLE
Fix .append(undefined) error, refs #213

### PR DESCRIPTION
**Pull request by fervero**

### CODE REVIEW

**Comment by fervero** [comment]
Huh.

Sorry about that, I assumed that `each` was a run-of-the-mill `forEach`, which would accept an empty array, do absolutely nothing, and not throw. (And if brevity of code is what you’re after, then a 3-character fix `|[]` would be hard to beat).

Ah well, it was worth a shot.

**Comment by fabiospampinato** [comment]
@fervero will you work on this PR further or should I close it?

**Comment by fervero** [comment]
Better close it, somehow I can't get tests to run at all in my environment.

On October 18, 2018, at 22:53, Fabio Spampinato <notifications@github.com> wrote:

@fervero will you work on this PR further or should I close it?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.￼

{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/kenwheeler/cash","title":"kenwheeler/cash","subtitle":"GitHub repository","main_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/header.png">https://assets-cdn.github.com/images/email/message_cards/header.png</a>","avatar_image_url":"<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>","action":{"name":"Open in GitHub","url":"<a href="https://github.com/kenwheeler/cash">https://github.com/kenwheeler/cash</a>"}},"updates":{"snippets":[{"icon":"PERSON","message":"@fabiospampinato in #215: @fervero will you work on this PR further or should I close it?"}],"action":{"name":"View Pull Request","url":"<a href="https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043">https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043</a>"}}} [ { "@context": "<a href="http://schema.org">http://schema.org</a>", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "<a href="https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043">https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043</a>", "url": "<a href="https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043">https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043</a>", "name": "View Pull Request" }, "description": "View this Pull Request on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "<a href="https://github.com">https://github.com</a>" } }, { "@type": "MessageCard", "@context": "<a href="http://schema.org/extensions">http://schema.org/extensions</a>", "hideOriginalBody": "false", "originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB", "title": "Re: [kenwheeler/cash] Fix .append(undefined) error, refs #213 (#215)", "sections": [ { "text": "", "activityTitle": "**Fabio Spampinato**", "activityImage": "<a href="https://assets-cdn.github.com/images/email/message_cards/avatar.png">https://assets-cdn.github.com/images/email/message_cards/avatar.png</a>", "activitySubtitle": "@fabiospampinato", "facts": [ ] } ], "potentialAction": [ { "name": "Add a comment", "@type": "ActionCard", "inputs": [ { "isMultiLine": true, "@type": "TextInput", "id": "IssueComment", "isRequired": false } ], "actions": [ { "name": "Comment", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"kenwheeler/cash\",\n\"issueId\": 215,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}" } ] }, { "name": "Close pull request", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"PullRequestClose\",\n\"repositoryFullName\": \"kenwheeler/cash\",\n\"pullRequestId\": 215\n}" }, { "targets": [ { "os": "default", "uri": "<a href="https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043">https://github.com/kenwheeler/cash/pull/215#issuecomment-431157043</a>" } ], "@type": "OpenUri", "name": "View on GitHub" }, { "name": "Unsubscribe", "@type": "HttpPOST", "target": "<a href="https://api.github.com">https://api.github.com</a>", "body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 392987400\n}" } ], "themeColor": "26292E" } ]

**Comment by fabiospampinato** [comment]
Are you on Windows? if so I've just updated the bundler that `cash` uses, it didn't support Windows properly, you should be able to bundle cash and run its tests under Windows now.

I'm closing this then, feel free to open a new one.

Ps. you might want to check your Emails+GitHub configuration, I think a JSON object got logged in your previous message which contained an API, I've deleted the message to avoid leaking that api key further, the object looked something like this:

```
{"api_version":"1.0","publisher":{"api_key":"XXXXXXXXXXX","name":"GitHub"},"entity":{"external_key":"github/kenwheeler/cash","title":"kenwheeler/cash","subtitle":"GitHub repository",
```

**Pull request closed without merging**
