### PR TITLE
Form cleanup

### PR DESCRIPTION
**Pull request by vivekimsit**
- Handle disabled field.

- Optimize select-single.

- Fix `value`.

### CODE REVIEW

**Comment by shshaw** [comment]
On [line 44 of forms.js](https://github.com/kenwheeler/cash/pull/140/files#diff-45050ae84458ce60bedcfd9bd36c8008R44), can you add ` || this` to allow for serializing collections of inputs that are not specifically form elements?

I'm going to dig further into the changes to make sure everything else from #116 is present and optimized. At first look, this seems to be a good improvement. Thanks, @vivekimsit.

**Comment by vivekimsit** [comment]
I don't get it `serializing collections of inputs that are not specifically form elements` can you please explain a bit. AFAIK we need to serialize only form elements here.

**Comment by shshaw** [comment]
Supporting `$( "input, textarea, select" ).serialize();` instead of `$('form').serialize();` for inputs that are not inside of a form or a specific collection of inputs. This is something that `jQuery.fn.serialize` supports.

**Comment by vivekimsit** [comment]
I will look into it then.

**Comment by vivekimsit** [comment]
@shshaw just one more thought, if we need to serialize the non-form elements, then in that case the code shouldn't go in forms.js, wdyt?

**Comment by shshaw** [comment]
`val` is in the same file which only deals with non-form elements. The file name is general enough, I don't think it needs to be renamed.

**Comment by shshaw** [comment]
I think I'm good with these changes. I'd like to look over it a little more to ensure it's consistent with the code style, but I may add this to the track for 1.3.5.

Thanks, @vivekimsit

**Comment by vivekimsit** [comment]
@shshaw can you please look into it?

**Pull request merged**
