### PR TITLE
cdn.jsdelivr.net/npm/cash-dom@3.0.0 -> cdn.jsdelivr.net/npm/cash-dom@3

### PR DESCRIPTION
**Pull request by limonte**
jsdelivr will provide the latest version of the current major, so users will automatically get all documented features and bug-fixes.

### CODE REVIEW

**Comment by fabiospampinato** [comment]
Thanks for the PR, but I think if our users want this behavior then they should decide to make this change for themselves. Since the readme describes a particular version of cash (the current one) I think it makes sense to link to the current version via jsdelivr.

**Comment by limonte** [comment]
Let's imagine this case:

1. a developer installs `cash` to his/her project by using the provided guide from the README:

```html
<script src="https://cdn.jsdelivr.net/npm/cash-dom@3.0.0"></script>
```

2. a month later they discover a bug and report it to this repo

3. @fabiospampinato needs to spend his precious time to read through the reported issue and close it with a message "fixed in 3.0.1, please bump the dependency"

The time of a developer is wasted, the time of @fabiospampinato is wasted.

So, if for some reason (I don't really understand it) you don't want users to automatically have new features, then at least let them have bug-fixed automatically.

**Comment by fabiospampinato** [comment]
- Regarding saving time: keep in mind that this conversation is also costing me some time. Something like your hypothetical scenario where I would waste time hasn't happened once yet. Also keep in mind that in order to make that change I would have to either 1) manually update the readme each time, potentially forgetting to do so sometimes, causing some other issues down the line or 2) updating [`bump`](https://github.com/fabiospampinato/bump) in order to make this automatable, which also requires some time (plus let's not forget about the downsides of making the tool more complicated, both because it will be a bit harder to maintain and harder to understand by the users).

- Regarding the "let them have bug-fixed automatically" part: nobody is preventing them to do so. And keep in mind that in the future we may publish v3.0.1, then v3.1.0, and then v3.1.1, in which case the bug fixes in v3.1.1, assuming they were present in v3.0.1 too, won't be available to people loading the 3.0.x version from jsdelivr. So in this regard encouraging the used of `@3.0.x` by default may even have the opposite effect as people may think that then they'll have all the bug-fixes published for the `3.x` release.

**Comment by limonte** [comment]
Fair enough, thanks for considering and explaining in details your opiinon @fabiospampinato

**Pull request closed without merging**
