### PR TITLE
Updated parseHTML which fixes the base url issue

### PR DESCRIPTION
**Pull request by softwarespot**
This is based on jQuery 3.0's implementation

### CODE REVIEW

**Comment by simeydotme** [comment]
thanks @softwarespot :D
could you please create a quick JSFiddle to demonstrate the before/after of this fix?

**Comment by shshaw** [comment]
What is the base URL issue you're referring to?

**Comment by softwarespot** [comment]
https://github.com/jquery/jquery/issues/2965, it's also in the jQuery source code.

**Comment by simeydotme** [comment]
looks smart :)
I'd like to run this through some tests before merging it, will keep you updated! :)

**Pull request merged**
