### PR TITLE
chore(package.json): add "files" to avoid publishing unnecessary files to npm

### LINKED ISSUE #286: Unnecessary files are published to npm
image

image

### PR DESCRIPTION
**Pull request by limonte**
Closes #286 

Docs: https://docs.npmjs.com/files/package.json#files

### CODE REVIEW

**Comment by limonte** [comment]
not sure if we need `"src"` folder to be published, @fabiospampinato ?

**Comment by fabiospampinato** [comment]
@limonte We don't need to publish `src`, but I think some other files should be published too: `CHANGELOG.md`, `LICENSE`, `package.json` and `README.md`

**Comment by limonte** [comment]
> We don't need to publish `src`

Removed.

> I think some other files should be published too: CHANGELOG.md, LICENSE, package.json and README.md

They are included by default, from https://docs.npmjs.com/files/package.json#files

> Certain files are always included, regardless of settings:
> - package.json
> - README
> - CHANGES / CHANGELOG / HISTORY
> - LICENSE / LICENCE
> - NOTICE
> - The file in the “main” field

**Comment by fabiospampinato** [comment]
Thanks! Available in v4.1.2.

**Pull request merged**
