### PR TITLE
Object for `$.fn.data`

### PR DESCRIPTION
**Pull request by shshaw**
Support setting multiple data key-value pairs on a collection with `$.fn.data` using an object (#95)

### CODE REVIEW

**Comment by simeydotme** [comment]
@shshaw shall we add this to the milestone? :)

**Comment by shshaw** [comment]
@simeydotme 1.3.0, you mean?

**Comment by shshaw** [comment]
@simeydotme @kenwheeler Since we have several pending pull requests that are ready to go as far as I'm concerned ( #83, #96, #109, #110, & #111 ), should we merge them all together into a single release? If so, should that be 1.3.0 or 1.2.2? 

There are a few new functionality pieces ( #83, #96, #110's remove all classes ) aside from the straight up bug fixes, so I'm thinking a merged 1.3.0 is the way to go.

**Comment by simeydotme** [comment]
good call.

**Comment by kenwheeler** [comment]
👍

**Pull request merged**
