### PR TITLE
Add data to trigger event

### PR DESCRIPTION
**Pull request by PeachIceTea**
This will accept an object as second parameter and copy all of that objects properties over. Maybe that is a little too simplistic as it could overwrite properties of the event. However I am not a fan of the way [CustomEvent](https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent) is done where you can only pass an object with a _detail_ property in. Of course we could just set the passed in object equals to _detail_ but that seems unnecessary.

### CODE REVIEW

**Comment by simeydotme** [comment]
@PeachIceTea ... I build apps with heavy usage on pub-sub.... basically my technique is;


```
var pubsub = $({});
pubsub.trigger("event");
pubsub.on( "event", function(){
});
```

But, along with that, we heavily use event data for useful cross-module decoupled communication.

```
// menu module
pubsub.trigger("menu.open", { name: "menu1" });

// tracking module
pubsub.on("menu.open", function(e, data) {
  trackOpen( data.name );
});
```
Contrived example, but accurate... so passing data around as a separate object is very important for me and my decoupled architecture.... smushing `data` into `event` seems a little awkward, any chance to investigate the same implementation jQuery uses?

**Comment by PeachIceTea** [comment]
Having used this the past couple of days I agree that attaching the data like I did feels unclean and awkward. First time looking into the jquery code but I think something similar should be doable. 
However I am wondering if it wouldn't be better to just put the data into event.data or event.details. It certainly would be a cleaner implementation.

**Comment by simeydotme** [comment]
Sounds reasonable, and as yoi say cleaner and more performant probably :)

**Comment by shshaw** [comment]
To help with jQuery compatibility, it would be great if the data could be passed as a separate argument to the callback instead of as a `data` property.

Since we can't use the current `initEvent` and `dispatchEvent` to pass along a separate object, we could hijack the original callback like we do with delegated events, and attach the data from `trigger` to a private property on the event, as to not interfere with any normal event data.

Something like this:

```js

  on(eventName, delegate, callback, runOnce) {
    var originalCallback = callback;
    ... 
    if ( delegate ) { 
      // do the data hijacking in the delegate hijacking, so we don't have to have multiple abstractions
    } else {
       callback = function(e) {
          var data = e[cash.uid];
          delete e[cash.uid];
          originalCallback(e,data);
       }
    }
    ...
  },

  trigger(eventName, data) {
    var evt = doc.createEvent("HTMLEvents");
    evt[cash.uid] = data;
    evt.initEvent(eventName, true, false);
    return this.each(v => v.dispatchEvent(evt));
  }

```

Any thoughts?

**Comment by shshaw** [comment]
@simeydotme Is your example how you actually do pubsub style triggers? Currently, event triggering doesn't work unless there are nodes in the cash collection since it's running a `this.each` call to attach the events. Does jQuery support events an empty collection like that?

**Comment by simeydotme** [comment]
yes @shshaw ... when looking for a good pubsub library before, I came across an article saying basically if you've got jQuery in your project, you don't need to install a separate pubsub, as you can just utilize jQuery's custom events... 

It's actually from Ben Alman (the legend) and you can see the original concept here:
https://gist.github.com/cowboy/661855

basically I don't need to alias to `.subscribe`, that's just syntactic sugar imo, just use `pubsub.trigger("")`.

**Comment by shshaw** [comment]
Interesting method. Unfortunately, it would take a lot of tweaking to make cash work with an object since it's so DOM based ( `data-set`, `getAttribute`, `addEventListener`, etc ). 

Like some of the comments suggested with Zepto compatibility, simply creating a new element to be the DOM event recipient would likely be the best workaround for this technique.

```
  var pubsub = $('<b/>');
  pubsub.on('event',function(e){ console.log(e); });
  pubsub.trigger('event');
```

**Pull request merged**
