### PR TITLE
Replace package-lock.json with yarn.lock, use Yarn in TravisCI

### LINKED ISSUE #220: Consider removing package-lock.json from repo
`package-lock.json` is a joke:

- https://stackoverflow.com/q/45022048/1331425
- https://github.com/npm/npm/issues/17979

### Current behavior

```
git clone git@github.com:kenwheeler/cash.git
npm install

git status

On branch remove-package-lock
Your branch is up to date with 'origin/remove-package-lock'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   package-lock.json

```

`package-lock.json` is changed, nonsense which only developers of `npm/cli` can understand :) Other people seem to be [confused](https://github.com/npm/npm/issues/18103#issuecomment-370401935):

image

### Expected behavior

Git working tree is clean, `package-lock.json` is the same.

### PR DESCRIPTION
**Pull request by limonte**
Closes #220

### CODE REVIEW

**Comment by limonte** [comment]
There's the speed improvement in Travis as well:

image

image

**Comment by fabiospampinato** [comment]
I'll have to document myself more about the shortcomings of `package-lock.json`, then I'll decide if this should be merged or not :+1:

**Comment by fabiospampinato** [comment]
I'm going to remove `package-lock.json`, but let's stick with `npm`.

**Comment by limonte** [comment]
> I'm going to remove package-lock.json, but let's stick with npm.

I guess you're not using `yarn` personally, because if you do you would love it :) But it's fine to keep npm, keep in mind that `npm ci` will not work without `package-lock.json`, you'll need to replace it with `npm i`.

**Comment by limonte** [comment]
@kenwheeler 

> keep in mind that `npm ci` will not work without package-lock.json, you'll need to replace it with `npm i`.

image

**Comment by fabiospampinato** [comment]
Yeah I'm working on the updated configuration right now 👍

**Pull request closed without merging**
