### PR TITLE
tests: use npm ci

### PR DESCRIPTION
**Pull request by DanielRuf**
`npm ci` is much faster and is meant for CI. This PR is meant for evaluating the new ci command and testig the performance and compare the logs of Travis CI.

https://docs.npmjs.com/cli/ci
http://blog.npmjs.org/post/171556855892/introducing-npm-ci-for-faster-more-reliable

### CODE REVIEW

**Comment by fabiospampinato** [comment]
We are now using Karma for testing.

If you feel using `npm ci` is still worthwhile please rebase on master and resubmit the PR and I'll take the time to review it 👍

**Comment by DanielRuf** [comment]
Please reopen so I can rebase. It does not matter if Karma or anything else is used as this is not relevant for this PR.

**Comment by DanielRuf** [comment]
Rebased and resolved the conflicts.

**Comment by DanielRuf** [comment]
> No tests are run, can you fix that?

Tests for 8 run, this is just some hiccup.

**Comment by fabiospampinato** [comment]
> Tests for 8 run, this is just some hiccup.

Right, sorry but as you might have guessed I'm not very familiar with Travis CI.

I've cherry picked the commits that are actually about travis, leaving out the updated `package-lock.json`, which seems unnecessary to me.

**Comment by DanielRuf** [comment]
> fabiospampinato closed this pull request 36 minutes ago

Any comment why this was closed?

**Comment by DanielRuf** [comment]
> I've cherry picked the commits that are actually about travis, leaving out the updated package-lock.json, which seems unnecessary to me.

For `npm ci` the lockfile has to be in sync so this is meeded, otherwise CI may fail due to npm.

**Comment by fabiospampinato** [comment]
In sync with what?

So far it looks like the build is [passing](https://travis-ci.org/kenwheeler/cash/builds/429193083?utm_source=github_status&utm_medium=notification), in case anything breaks because of our dependencies I'll get back to this.

**Comment by DanielRuf** [comment]
> In sync with what?

In sync with the package.json.

**Pull request closed without merging**
