### PR TITLE
Fixed delegated events to receive the event object

### PR DESCRIPTION
**Pull request by tjbenton**
```js
$('ul').on('click', (event) => console.log(e)) // this would log the event as expected

$('ul').on('click', 'li', (event) => console.log(e)) // this would log as undefined because the original event wasn't being passed through
```

This 2 line change fixes that bug.

### CODE REVIEW

**Comment by softwarespot** [comment]
Maybe squash the commits into one.

**Comment by shshaw** [comment]
What's the significance of the change on [line 51](https://github.com/kenwheeler/cash/pull/91/files#diff-4607e46b15da8ae44c4b47730c6d5963R51)? Delegate events should stop at the parent element ( `this` ), not the root ( `documentElement` ).

**Comment by tjbenton** [comment]
@shshaw I was getting an error when I would delegate an event from the document. I came across this error when using cash with JSPM.

```
import $ from 'cash'
$(document).on('click', 'a', (e) => {
  e.preventDefault();
  console.log('clicked');
});
```

screen shot 2016-04-26 at 2 01 44 pm

**Comment by shshaw** [comment]
Perhaps a better check would be `if (t === this || !t.parentNode) {` since that seems to be the issue, calling `matches` on a `null`.

**Comment by tjbenton** [comment]
since it's an issue with the match function what about just updating the match function so that this issue doesn't happen in other cases where the match function used.

```js
function matches(el, selector) {
  return (el || {}).tagName && (
    el.matches || 
    el.webkitMatchesSelector || 
    el.mozMatchesSelector || 
    el.msMatchesSelector || 
    el.oMatchesSelector
  ).call(el, selector);
}
```

If I update the `matches` function to check if the element has a `tagName` it solve my problem because `document` is not an element so it doesn't have a `tagName`. The `(el || {})` piece will handle any null values that are passed as well.

**Comment by shshaw** [comment]
Good thought. Here are some other ways we might could approach this:

Option 1:
```javascript
// Check if el isn't null/undefined, fallback to a simple `return false` if no matches available
function matches(el, selector) {
  return el && (
    el.matches || 
    el.webkitMatchesSelector || 
    el.mozMatchesSelector || 
    el.msMatchesSelector || 
    el.oMatchesSelector || 
    function(){ return false; }
  ).call(el, selector);
}
```

Option 2:
```javascript
// Cache the browser's matches function
var el = document.createElement('div'),
      _matches = ( el.matches || el.webkitMatchesSelector || el.mozMatchesSelector || el.msMatchesSelector || el.oMatchesSelector );

function matches(el, selector){
   return el && !!el.tagName && _matches.call(el,selector);
}
```

**Comment by tjbenton** [comment]
I decided to do a little bit of testing for performance and here are my results. I would have just done a jsperf for it but the [site](http://jsperf.com/) is currently down so sorry in advance for the long message.

#### Chrome
###### matches1
  - times: 71.003ms, 53.969m, 58.557m, 51.012ms
  - average: 58.63525ms
  
###### matches2
  - times: 49.852ms , 50.645ms, 53.898ms, 47.603ms
  - average: 50.499500000000005ms
  
###### matches3
  - times: 53.338ms, 50.802m, 52.723m, 55.512ms
  - average: 53.09375ms

#### FireFox
###### matches1
  - times: 140.48ms, 137.26ms, 138.2ms, 138.8ms
  - average: 138.685ms
  
###### matches2
  - times: 135.22ms, 141.78ms, 133.11ms, 131.79ms
  - average: 135.475ms
  
###### matches3
  - times: 137.88ms, 127.66ms, 126.25ms, 131.5ms
  - average: 130.8225ms

<br>
<hr>
<br>
I would suggest going with `matches3` because it's 50+ characters smaller in size and the performance gain from caching `_matches` isn't enough to warrant it. 

<br>
<hr>
<br>

### matches 1
Character count: 303
```js
let matches1;
{
  let e = document.createElement('div'),
      _matches1 = ( e.matches || e.webkitMatchesSelector || e.mozMatchesSelector || e.msMatchesSelector || e.oMatchesSelector );

  matches1 = function matches1(el, selector) {
    return el && !!el.tagName && _matches1.call(el, selector);
  };
}
```

### matches 2
Character count: 291
```js
let matches2;
{
  let e = Element.prototype,
      _matches2 = ( e.matches || e.webkitMatchesSelector || e.mozMatchesSelector || e.msMatchesSelector || e.oMatchesSelector );

  matches2 = function matches2(el, selector) {
    return el && !!el.tagName && _matches2.call(el, selector);
  };
}

```

### matches 3
Character count: 238
```js
function matches3(el, selector) {
  return el &&
    !!el.tagName && (
      el.matches ||
      el.webkitMatchesSelector ||
      el.mozMatchesSelector ||
      el.msMatchesSelector ||
      el.oMatchesSelector
    ).call(el,selector);
}
```

Here's an example of what I used to run the tests.

```js
console.time('matches1');
for (var i = 0; i < 10000; i++) {
  matches1(document, 'html')
  matches1(document.documentElement, 'html')
  matches1($('a')[0], 'html')
}
console.timeEnd('matches1');
```

**Comment by shshaw** [comment]
Just to clarify since it's not a standard JSPerf test: lower numbers means more performant, correct?

Your character counts aren't quite accurate because you're using quite different syntax for the first two matches, and the real impact is going to be on minified size which I like to test with [Closure Compiler](http://closure-compiler.appspot.com/home) for quick checks. Here are the results:

- matches1: 186 characters
- matches 2: 183 characters
- matches 3: 157 characters

Thinking through it some more, here's a variant that meets the requirements of failing gracefully on `document` and other non-matchable items and will compress down to 156 characters or less when minified.

- matches 4: 156 characters

```
function matches4(el, selector) {
  var m = el && (
    el.matches ||
    el.webkitMatchesSelector ||
    el.mozMatchesSelector ||
    el.msMatchesSelector ||
    el.oMatchesSelector
  );
  return !!m && m.call(el, selector);
}
```

We're basically splitting bytes at this point, but I think this may be better than checking for the `tagName`, since we're looking exactly for what's needed: Does `el` exist, does it have a `matches` function, and does `el` match the `selector`?

**Comment by tjbenton** [comment]
I tried it out and it seems to fix the issue I was having. I'll go ahead and add that in there. 

I noticed when I ran `gulp` that there're 2 jshint errors exist. 1 for the `on` function having to many arguments which it needs and the other was `fn` is defined but not used, which it is being used when the files get combined together. Would you like me to add `// jshint ignore:line` on those lines to remove the errors or should I just leave them to you?

**Comment by shshaw** [comment]
Please do! They're BS warnings that I couldn't get around with regular JSHint rules. Didn't know about the ignore line feature!

**Comment by shshaw** [comment]
Also, please give the package.json a version number bump to 1.2.2 before you build, and I'll merge the pull request.

**Comment by kenwheeler** [comment]
@shshaw moving forward, thoughts on a release schedule? weekly, bi weekly?

**Comment by tjbenton** [comment]
I messed up with the git stuff so the fixes I have didn't actually get merged.

**Comment by shshaw** [comment]
@tjbenton No worries, just shoot over another pull request when you've got it.

**Comment by tjbenton** [comment]
Do you want me to open up a new pull request and change the version to be `1.2.3`?

**Comment by shshaw** [comment]
@tjbenton Still just 1.2.2.

**Comment by shshaw** [comment]
@kenwheeler I don't know that there will be enough of a constant flow of new features or bug fixes to have a set release schedule like weekly or biweekly.

We should combine releases where possible instead of a new release for each feature or fix, but I'd rather push out [patch releases](http://semver.org/) ( version 1.2.x ) as they are available & tested, especially for bug fixes.

Larger changes we'll have to plan out and communicate ( version 1.3 or version 2 ), but I don't know that we'll have a specific schedule since it will be more based on where cash needs to be taken.

**Pull request closed without merging**
