### PR TITLE
.attr() method improvements

### PR DESCRIPTION
**Pull request by simeydotme**
noticed while writing unit tests that this method doesn't really behave how I'd expect.

1. `collection` was being returned when argument was falsey/integer
2. `null` was being returned when attribute was not found.

fixed/changed behavior to return `undefined` instead of `null`, and `undefined` instead of collection when attempting to check for `falsey` or `integer.

### CODE REVIEW

**Comment by simeydotme** [comment]
by the way, modifying these methods takes way longer than needed because of understanding and dancing-around ternary statements ... hella confusing, and unecessary?

**Comment by rwwagner90** [comment]
@simeydotme I was also about to make some changes to the `.attr` method. I have an issue where `this[0]` is undefined, and I end up with `TypeError: Cannot read property 'getAttribute' of undefined`. Any chance you could put a check for `this[0]` existence in there?

**Comment by simeydotme** [comment]
you mean running a `.attr()` on an empty collection?

**Comment by shshaw** [comment]
Or possibly on window or document? Not sure that those will have
getAttribute.

**Comment by simeydotme** [comment]
@shshaw it works fine on `window` and `document` :)

**Comment by rwwagner90** [comment]
@simeydotme we specifically migrated from jquery to cash. There were no errors with jquery, but cash was giving us an error. We worked around it, but jquery did handle this for us.

**Comment by simeydotme** [comment]
@rwwagner90 , thats great news for your users! :D 

I would like to get to the bottom of what you're talking about, if you say jQuery wasn't giving an error, then it must not be the empty-collection scenario... so if you could create a JSFiddle, or anything, to help reproduce... that'd be awesome :)

**Comment by rwwagner90** [comment]
@simeydotme it was the case of trying to select elements where none existed. We had an empty `ul` with no `li` inside, and we were doing something like `$('ul li').attr({foo:bar})`, and therefore `this[0]` was not a thing. You could argue that it is on us to ensure something was selected before calling `attr`, but jQuery just ignores it and keeps going, rather than throwing an error.

**Comment by shshaw** [comment]
I don't know that the [`&& name !== ''` check](https://github.com/kenwheeler/cash/pull/111/files#diff-c4c92b97ff60ec14a1199df1f5ae644eR33) is necessary. Chrome, at least, just returns `null` when `getAttribute('')` is called. Or is that check for `setAttribute`? If so, that should be down lower so that the `for` loop isn't potentially called on the empty string.

Also, the check on [line 38](https://github.com/kenwheeler/cash/pull/111/files#diff-c4c92b97ff60ec14a1199df1f5ae644eR38) likely isn't necessary either. Just return the `getAttribute` results, which should be `null` if it doesn't exist.

And the `ret` variable doesn't seem to actually be doing anything. Was that perhaps supposed to be set in the `getAttribute` area? I think `this` should be returned to maintain chainability unless a `getAttribute` request was made.

Regarding @rwwagner90's bug, a check for `this[0]` existing should be added before. 

Working on some revisions now. Let me know if you have any thoughts.

**Comment by simeydotme** [comment]
wait a sec, @shshaw ... everything you said is how it _WAS_ working, I wrote tests based on the principle that the method should return `undefined` (not `null`) for non-existent attributes, just as jQuery does... I understand it's not really necessary to completely match jQuery, but in high-traffic api areas I think it's good to return an intuitive result... when you "get" an attribute, you should never expect the result to be a collection. Take this for example:

```js
// <body> (no attributes)
var x = $("body").attr("x");
if( x ) { // do something }
```
The developer should _not_ expect the result to be a collection, as that would be truthy... and cause problems.

I also think that so many people switching would already be checking for `undefined` , so returning `null` would be a pain for them.

**Comment by shshaw** [comment]
With what I'm proposing, you will receive `null` instead of `undefined` if `getAttribute` does not return anything, which should work as expected for developers.

In the case of @rwwagner90's bug, if the elements do not exist, should it return `null`, `undefined` or the collection?

**Comment by shshaw** [comment]
Here's my modified version so far. The only difference shoudl be returning `null` instead of `undefined` for `getAttribute` calls for attributes that aren't set. 

```
  attr(name, value) {
    if ( isString(name) ) {
      if ( value === undefined ) {
        return ( this[0] ?
            this[0].getAttribute ?
              this[0].getAttribute(name) : this[0][name]
            : undefined );
      }

      return this.each(v => {
        if ( v.setAttribute ) { v.setAttribute(name, value); }
        else { v[name] = value; }
      });
    }
    for (var key in name) {
      this.attr(key,name[key]);
      return this;
    }
  },
```

**Comment by simeydotme** [comment]
I think what I have now is pretty good (check last commit), it passes all the tests and matches expectation of someone converting from jQuery.

**Comment by shshaw** [comment]
It was still failing on the @rwwagner90 bug. Check out [pr/111 branch](https://github.com/kenwheeler/cash/tree/pr/111)

**Comment by simeydotme** [comment]
nice, merged that in! :D

although, I'm still foggy on what @rwwagner90 's actual issue is, I haven't been able to reproduce it... I'd love to test it :)

**Comment by shshaw** [comment]
If you run `$.fn.attr` on an empty collection, it was giving an error.

You can test it on the test page if you run `attr` on any other selector that won't have any matches ( `$('ul li')` or `$('#fakeID')` for instance). With the updated code, it will return `undefined` or `null` when attempting to get an attr ( `$('#fakeID').attr('hi')` ), or will just return the empty collection when trying to set attributes ( `$('#fakeID').attr('hi', true);` ) instead of causing an error.

**Comment by simeydotme** [comment]
ah ok, sweet :) :+1:

**Comment by rwwagner90** [comment]
@shshaw can you release 1.3.0 on npm please?

**Comment by shshaw** [comment]
I believe that's something @kenwheeler will have to do. I don't have control of the npm package on npmjs.com

**Comment by rwwagner90** [comment]
@kenwheeler it would be much appreciated!

**Comment by kenwheeler** [comment]
@shshaw are we good to go?

**Comment by rwwagner90** [comment]
Also, should something like this work?

```js
 const listItemOpts = {
        attrs: {
          class: 'job-result',
          itemprop: 'itemListElement',
          itemtype: 'http://schema.org/JobPosting'
        }
      };

this.$el.find('li.ui-list-item')..attr(listItemOpts.attrs);
```

I am not seeing any of the attrs applied to any of the elements in that collection. Did this PR fix this?

**Comment by rwwagner90** [comment]
Looks like it's not supported and I have to do something like:

```js
 for (const attr of Object.keys(this.listItemOpts.attrs)) {
        $listItems.attr(attr, this.listItemOpts.attrs[attr]);
      }
```

**Comment by shshaw** [comment]
@kenwheeler 1.3.0 is tested, tagged & released. Good for pushing to npm. 

@rwwagner90 Taking a look at this. Not immediately sure why that wouldn't work.

**Comment by rwwagner90** [comment]
@shshaw there doesn't appear to be any iterating through an object passed in. It's simply able to do a 1:1 mapping of attrs and set them. I can't pass JSON with several key/value pairs to be set.

**Comment by shshaw** [comment]
@rwwagner90 It's working as I'm testing it now. Are you using the 1.3.0 branch?

```
var listItemOpts = {
        attrs: {
          class: 'job-result',
          itemprop: 'itemListElement',
          itemtype: 'http://schema.org/JobPosting'
        }
      };

$('body').find('li').attr(listItemOpts.attrs);
```
Works on the test suite's page, ./test/index.html

**Comment by kenwheeler** [comment]
@shshaw published

**Comment by rwwagner90** [comment]
@shshaw I was using 1.2.0 because 1.3.0 wasn't on npm yet. It's possible it was fixed in this PR. That's what I was trying to find out.

**Comment by rwwagner90** [comment]
@shshaw it does work with the new version 👍

**Comment by shshaw** [comment]
@rwwagner90 Great to hear! Let us know if you catch anything else.

**Pull request merged**
